import time

def Main_Plot(p):
    if p == 0:#打開敘述
        print("Hello! World!")
        time.sleep(1)
        print("\n注意: 此遊戲並未有任何閃光元素")
        print("          全年齡皆可遊玩!",end = "")
        time.sleep(1)
        print("~",end = "")
        time.sleep(1)
        print("~",end = "")
        time.sleep(1)
        print("~",end = "")
        time.sleep(1)
        print("MADE  by  PYTHON")
        time.sleep(2)
        for i in range(10):
            print("\n")
            if i >= 5:
                print("\n")
            time.sleep(0.2)
    if p == 1:#相遇
        print("你是個上班族")
        time.sleep(1)
        print("在你下班的途中，你在地上撿到了一顆蛋")
        time.sleep(1.5)
        print("你覺得這是一些小屁孩畫上的，但是這真實的外觀使你一下就拋除了這個猜想")
        time.sleep(3)
        print("看著看著，突然來了一股奇怪的吸引力")
        time.sleep(1.5)
        print("這迫使你把這顆蛋帶回家......")
        time.sleep(2.5)
    if p == 2:#最佳的照顧
        print("你好奇的打量這顆蛋，這顆雞蛋上的閃電條紋越來越吸引你的注意力")
        time.sleep(2.5)
        print("你給他最好的枕頭，最好的燈光，最棒的角落，使這顆雞蛋受到最完美的照顧")
        time.sleep(2.5)
    if p == 3:#一大衝擊
        print("你不小心讓這顆雞蛋從枕頭上滾了下來，你無法忍受最完美的蛋竟然染上的髒汙")
        time.sleep(3)
        print("你幫這顆蛋小小清潔了一下")
        time.sleep(2)
        print("結果",end = "")
        for i in range(5):
            time.sleep(1)
            print(".",end = "")
        time.sleep(1)
        print(".")
        print("閃電的符號被你清除掉了......")
    if p == 4:#出生
        print("哇!!  你親眼見證小雞啄破蛋殼的畫面")
        time.sleep(2)
        print("你以為這顆蛋能為這世界做出貢獻")
        time.sleep(2)
        print("結果孵化出來的是",end = "")
        for i in range(5):
            time.sleep(1)
            print(".",end = "")
        time.sleep(1)
        print(".")
        time.sleep(1)
        print("一隻平凡的(黃色)小雞")
        time.sleep(1)
    if p == 5:#過於平凡
        print("這隻(黃色)小雞無時無刻都在提醒你這只是一隻(黃色)小雞")
        for i in range(5):
            time.sleep(1)
            print(".",end = "")
        time.sleep(1)
        print(".")
    if p == 6:#遺棄
        print("你受不了了")
        time.sleep(1)
        print("這隻雞實在太過平凡")
        time.sleep(1.5)
        print("就跟電子雞一樣")
        time.sleep(1)
        print("在風雨閃電交加的夜晚你遺棄了這隻(黃色)小雞")
        time.sleep(2.5)
    if p == 7:#Gameover?
        print("GameOver 你覺得呢")
        time.sleep(2)
        print("也許牠的確非常的平凡")
        time.sleep(2)
        print("蛋是有沒有可能只是牠的時機還沒到",end = "")
        for i in range(5):
            time.sleep(1)
            print(".",end = "")
        time.sleep(1)
        print(".")
    if p == 8:#再次相遇
        print("昨天晚上的閃電還真多啊!你心想")
        time.sleep(2)
        print("也許那隻(黃色)小雞已經被雷劈死了吧!")
        time.sleep(2)
        print("要上班時，在你的腳下聽到的一股熟悉的聲音")
        time.sleep(2.5)
        print("當你不耐煩往下看的時候，你就突然被電暈了")
        time.sleep(2.5)
        print("當你再次醒來，發現地上有一隻小雞")
        time.sleep(2)
        print("這隻小雞渾身覆蓋著閃電")
        time.sleep(2)
        print("這隻雞跟那隻黃色小雞天差地遠")
        time.sleep(2)
        print("除了眼睛長的一樣，顏色也一樣，大小也一樣，走路的方式也一樣，叫聲也一樣",end = "")
        for i in range(5):
            time.sleep(1)
            print(".",end = "")
        time.sleep(1)
        print(".")
        print("算了，反正一定是不同隻")
        time.sleep(2)
        print("你重新將這隻")
        time.sleep(1)
        print("阿!被電!")
        time.sleep(2)
        print("你用絕緣手套重新將這隻")
        time.sleep(1)
        print("No!我不認識牠")
        time.sleep(2)
        print("你用絕緣手套將這隻(黃色)小雞帶回了你的")
        time.sleep(1)
        print("Noooooooo!")
        time.sleep(2)
        print("你用絕緣手套將這隻小雞帶回了你的住所後就匆匆忙忙的趕著去上班了")
        time.sleep(3)
    if p == 9:#啟程
        print("你辭去了工作")
        time.sleep(2)
        print("因為你與小雞")
        time.sleep(1)
        print("不")
        time.sleep(2)
        print("你與雷抗雞的冒險才剛剛開始")
